site_name: Blades in the Dark
# TODO UPDATE URL
# site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  icon:
    logo: material/sword-cross
  features:
    - navigation.indexes
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - autolinks
  - blog:
      blog_dir: journal
  - search
