site_name: Blades in the Dark
site_url: https://binaryman32.github.io/blades-in-the-dark-2025
repo_url: https://github.com/BinaryMan32/blades-in-the-dark-2025
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
watch:
  - data/
  - main.py
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  icon:
    edit: material/lead-pencil
    logo: material/sword-cross
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.indexes
    - navigation.tabs
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - macros:
      include_yaml:
        - characters: data/characters.yaml
  - autolinks
  - backlinks_section:
      ignore_links_from:
        - index.md
      ignore_links_to:
        - journal/**/*.md
  - blog:
      blog_dir: journal
  - search
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
