site_name: Blades in the Dark
site_url: https://binaryman32.github.io/blades-in-the-dark-2025
repo_url: https://github.com/BinaryMan32/blades-in-the-dark-2025
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  icon:
    edit: material/lead-pencil 
    logo: material/sword-cross
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.indexes
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - autolinks
  - blog:
      blog_dir: journal
  - search
